use env.yml
because pip does not support pygpu?
ERROR: Could not find a version that satisfies the requirement pygpu==0.6.4 (from -r requirements.txt (line 53)) (from versions: none)
ERROR: No matching distribution found for pygpu==0.6.4 (from -r requirements.txt (line 53))

https://github.com/roebius/deeplearning_keras2/issues/3